-- FIRE planner schema upgrade (PostgreSQL)
-- Run manually after deploying upgraded FIRE planner code.

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS retirement_age INTEGER NOT NULL DEFAULT 55;

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS multiplier DOUBLE PRECISION NOT NULL DEFAULT 33.0;

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS inflation_rate DOUBLE PRECISION NOT NULL DEFAULT 0.06;

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS safety_buffer DOUBLE PRECISION NOT NULL DEFAULT 1.2;

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS recommendation_flags TEXT NOT NULL DEFAULT '';

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS expected_return DOUBLE PRECISION NOT NULL DEFAULT 0.10;

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS return_source VARCHAR(16) NOT NULL DEFAULT 'system';

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS insurance_coverage DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS insurance_gap BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS tax_suggestions TEXT NOT NULL DEFAULT '';

ALTER TABLE fire_plans
ADD COLUMN IF NOT EXISTS monthly_plan TEXT NOT NULL DEFAULT '';

ALTER TABLE financial_profiles
ADD COLUMN IF NOT EXISTS insurance_coverage DOUBLE PRECISION NOT NULL DEFAULT 0;
